### ISSUE TITLE
NAF - Armoured vehicles should have camonets on by default (Arctic/Desert)

### ISSUE THREAD

**Issue by Saborknight** [2bnb/2bnb-factions#19]

**Comment by See0ne** [comment]
What
==========
Appears to not just be limited to the camonets not showing up - CV90s have got 50% to spawn with slat cages but I have not encountered this happening, both in mission and when spawning numerous to test

Why
==========
Unsure as of now - will need further investigation

**Comment by Saborknight** [comment]
So, there's another component to that Animations array, and that is a piece of code in the init which activates the Animation change.
However, in my testing I couldn't get it to work for a mod based config, only in a mission's description.ext file....
So my research hit a dead end resulting in that likelihood percentage being useless.

The only solution I know that will work is by changing the starting animation case in the Animations config for the individual vehicle.

This is exactly what I did for the M113s in NAF to remove the CIP/IFF panels. I'll have a look for the commit

**Comment by Saborknight** [comment]
https://github.com/2bnb/2bnb-extras/commit/fe343270f1ab1ea40d943e1ee259b1411f9ed916#diff-77EE37F73893D28C47CD4E65A29BACFER1055

Note the config is called `AnimationSources`
