### ISSUE TITLE
2 Faction sub categories not showing in Zeus

### ISSUE THREAD

**Issue by Amateur-God** [2bnb/2bnb-factions#35]
MTP and Desert, factions not showing up in zeus but show up in 3den.

**Comment by Saborknight** [comment]
That'll be a scope issue. From memory scope 2 is Eden only, and scope 3 is Zeus and Eden? Can't remember exactly, but recommend you check that

**Comment by Amateur-God** [comment]
> That'll be a scope issue. From memory scope 2 is Eden only, and scope 3 is Zeus and Eden? Can't remember exactly, but recommend you check that

 I haven't set a scope for CfgGroups or For EditorSubCategories as I didn't think they recognised scope as a valid input option

**Comment by Saborknight** [comment]
If that's the case, then the scope is either inherited from a parent class or is just the default, whatever that may be

**Comment by Amateur-God** [comment]
ill try setting a scope and see if it fixes it, never had to set scope before though which is strange

**Comment by Amateur-God** [comment]
possibly TFAR Radios breaking the mods

**Comment by Amateur-God** [comment]
confirmed wasnt tfar radios, all groups are now exactly the same with the exception of camo and still only woodland showing up,

further investigation required

**Comment by Amateur-God** [comment]
found the issue it was just C++ being an inconsistent finicky bitch and requiring them to be in the units[] = {} to show in zeus however never had that happen before
