### ISSUE TITLE
Schrödingers Magazine Fix/Compatch

### ISSUE THREAD

**Issue by magssibbert** [2bnb/2bnb-factions#36]
add Comppatch/Fix
add the 3CB magazines to STANAG_556x45 in cfgMagazineWells

see: https://discord.com/channels/532683310409842728/1130551301135159406/1130637640862015609

**Comment by Amateur-God** [comment]
@magssibbert exactly which weapons do you have this issue on? preferably the class names of the weapons as I haven't had this issue with the A3

**Comment by magssibbert** [comment]
> @magssibbert exactly which weapons do you have this issue on? preferably the class names of the weapons as I haven't had this issue with the A3

In my example it was the " UK3CB_BAF_L85A2_RIS_G " 
idk which other weapons would be impacted aswell

**Comment by Amateur-God** [comment]
okie, i will look into this and try and see what other weapons are affected and get a fix pushed

**Comment by Amateur-God** [comment]
attempted fix in #40

**Comment by Amateur-God** [comment]
apparently bug still persists however i have been unable to replicate the bug, need further feedback from @magssibbert regarding what exactly he is doing which is causing the bug

**Comment by Amateur-God** [comment]
this is a 3CB issue which can't be easily resolved in Factions, The CfgMagazineWells patch did not work and this is an issue with 3CBs configs which I could only fix by completely rewriting them which would likely then cause other issues with other 3CB mods.

please go to https://forums.bohemia.net/forums/topic/182771-3cb-baf-equipment/ and ask them to fix it
