### ISSUE TITLE
Reduce L85 variants weight (3CB)

### ISSUE THREAD

**Issue by Qaiten** [2bnb/2bnb-factions#38]
**Description:**
Currently the L85 weighs more than 2.5KG heavier than the C8 (L119) in 3CB. If we can make it even it would be better for both weights of current kits and would prevent people swapping to the C8 once released for an advantage and those who want a bullpup in their lives won't be punished with an extra 2KG.

**Information Reference:**
- Stormwire

**Comment by Qaiten** [comment]
Do you have any update on this @Amateur-God?

**Comment by Amateur-God** [comment]
Not yet, I shall be having a look at it sometime this week

**Comment by Amateur-God** [comment]
completed in #40
