### ISSUE TITLE
The NVG`s have em make the Splinter Cell sound

### ISSUE THREAD

**Issue by Hex9909** [2bnb/2bnb-factions#39]
**Arma 3 Version:** `1.xx` (stable / rc / dev)
**2BNB Factions Version:** `1.x.x` (stable / dev + commit hash)
**2BNB Modpack Version:** `1.x.x`

**Description:**
Add a detailed description of the error. This makes it easier for us to fix the issue.

**Steps to reproduce:**
- Add the steps needed to reproduce the issue.

**Where did the issue occur?**
- 2BNB Server / Zeus / 3DEN Editor / Virtual Arsenal

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file.

**Screenshots/Video:**
- Put cursor here and drag/drop image, or put a link to a [youtube](https://youtube.com) video here.

**Comment by Amateur-God** [comment]
will need to have a play around and figure out how to do this

**Comment by Amateur-God** [comment]
i offer you this as a potential optional mod so only people that want the nvg sound get it https://steamcommunity.com/sharedfiles/filedetails/?id=1391503269

**Comment by Amateur-God** [comment]
@Hex9909
